package main.java.problems;/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Euler2 {
    public static final int fib_max = 4000000;

    public static void solve() {
        int sum = 0;
        int last = 0;
        int next_fib;
        for (int i = 1; i <= fib_max; i = next_fib) {
            if (i % 2 == 0) {
                sum += i;
            }
            System.out.println("Current fib: " + i);
            if (i == 1) {
                next_fib = i + i;
            } else {
                next_fib = i + last;
            }
            last = i;
        }
        System.out.println("\n\nSum = " + sum);
    }
}
