/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */

package main.java.problems;

public class Euler12 extends Euler {
    private final int target = 500;

    @Override
    public void solve() {
        int i = 1;
        int lastSum = 1;
        int count;
        int naturalNumber;

        do {
            count = 1;
            i++;
            naturalNumber = lastSum + i;
            int x;
            if (naturalNumber % 2 == 0)
                x = 2;
            else
                x = 1;

            for (x;  x < naturalNumber; x += 2)
                if (naturalNumber % x == 0)
                    count++;
            System.out.println(naturalNumber + " has " + count + " divisors");
        } while (count < target);
    }
}
